### ISSUE TITLE
Ideas 

### ISSUE THREAD

**Issue by Konlab** [FlareHAX0R/deltaOS#13]
- [x] Clicking on the username on the desktop to open the user manager
- [ ] the settings api could look in the users/set/username/settings first, then if it don't finds the file it looked for look in the current default settings folder
- [ ] logout and api reload button
- [ ] custom non tabbed multitasking like in android but with a key not a button

**Comment by FlareHAX0R** [comment]
Ok. I'll consider these.

**Comment by Konlab** [comment]
How do I change the name of the issue?

**Comment by FlareHAX0R** [comment]
1:  Ehh... Possibly
2: I'd do that.
3: Possibly.
4: Probably not.

**Comment by FlareHAX0R** [comment]
Ok. Added your first idea.

**Comment by FlareHAX0R** [comment]
DeltaOS is being... discontinued.
https://floobits.com/FlareHAX0R/Delta/
Look at that for the new Delta(OS).
