### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Konlab** [FlareHAX0R/deltaOS#15]
Version: latest develop as of now (2015.3.29 19:40 GMT + 1 + summer time)
'Then excepted line 720~'
when then is added:
end excepted to close function at line 135

**Comment by FlareHAX0R** [comment]
Error code?

**Comment by Konlab** [comment]
I said:
then excepted line 721 if I remember correctly

**Comment by Konlab** [comment]
Yes, it's line 721 but the "if" is in line 720

**Comment by FlareHAX0R** [comment]
I mean the 3-letter string at the bottom right of the BSoD

**Comment by Konlab** [comment]
No BSoD it just came after the deltaOS string

**Comment by Konlab** [comment]
Before I could log in

**Comment by Konlab** [comment]
I downloaded deltaOS
completed ftsetup
after auto-rebooting in ft-setup got a normal deltaOS text in the middle of the screen and then got the error written red. No BSoDs. No exception catchers. Just the classic CraftOS error format.

**Comment by FlareHAX0R** [comment]
ohk.

**Comment by FlareHAX0R** [comment]
Fixed.
