### ISSUE TITLE
crash report #2

### ISSUE THREAD

**Issue by Konlab** [FlareHAX0R/deltaOS#18]
dialog:115: attempt to compare nil with nuber
error code on the ottom right: 318
deltaOS build: beta 1.0 (current)
this happened when I clicked the shutdown button

**Comment by FlareHAX0R** [comment]
318. got it.

**Comment by FlareHAX0R** [comment]
Hmmm. Ok.

**Comment by FlareHAX0R** [comment]
Excite Desktop will fix this.
