### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Konlab** [FlareHAX0R/deltaOS#9]
Hi!
just begun to play minecraft again and decided to download deltaos on my computer and I just found a bugi in users api: changing password removes root. I found the error but I have no time for fix until friday or saturday. So plz fix it or if u don't have time i'll do it on friday.

**Comment by FlareHAX0R** [comment]
(root really does not matter currently, you can just create users from the lua program.)

**Comment by Konlab** [comment]
ok

**Comment by Konlab** [comment]
Fixed
